# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kurzius Class Notes
author: William Kurzius
# email: wkurzius@manvillesd.org
# description: >- # this means to ignore newlines until "baseurl:"
#  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mr.kurzius.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima

minima:
  nav_pages:
    - this-week.md
  toggle: true

plugins:
  - jekyll-feed
  - jekyll-relative-links

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true


# this week data

this-week-dates: "Sep. 21–25"

cal-h: "[**AP Calc**](./ap-calculus/){: title=\"Course Page\"}<br>
        [<i class=\"fa-solid fa-file-lines\"></i>](./ap-calculus/ap-calc-syllabus.html){: title=\"Course Syllabus\"}"
cal-1: "**T**{: .day}[1.4 Continuity and One-Sided Limits](./ap-calculus/1-4-continuity-and-one-sided-limits.html)"
cal-2: "**R**{: .day}AP Progress Check: Unit 1 MCQ Part A"
cal-3: ""
cal-x: "Sep. 28"

csa-h: "[**AP Comp Sci A**](./ap-comp-sci-a/){: title=\"Course Page\"}<br>
        [<i class=\"fa-solid fa-file-lines\"></i>](./ap-comp-sci-a/ap-csa-syllabus.html){: title=\"Course Syllabus\"}
        [<i class=\"fa-solid fa-globe\"></i>](https://runestone.academy/ns/books/published/manvillehighschool_csawesome2_2526/csawesome2.html){: target=\"_blank\"}{: title=\"CSAwesome2 Online Book\"}"
csa-1: "**M**{: .day}Quiz 1"
csa-2: "**W**{: .day}[1.5 Casting and Ranges of Values](./ap-comp-sci-a/1-5-casting-and-ranges-of-values.html) and [1.6 Compound Assignment Operators](./ap-comp-sci-a/1-6-compound-assignment-operators.html)"
csa-3: "**F**{: .day}[1.7 APIs and Libraries](./ap-comp-sci-a/1-7-apis-and-libraries.html) and [1.8 Documentation with Comments and Preconditions](./ap-comp-sci-a/1-8-documentation-with-comments-and-preconditions.html)"
csa-x: "Sep. 21/Oct. 5"

geo-h: "[**Geometry**](./geometry/){: title=\"Course Page\"}<br>
        [<i class=\"fa-solid fa-file-lines\"></i>](./geometry/geometry-syllabus.html){: title=\"Course Syllabus\"}"
geo-1: "**M**{: .day}Benchmark"
geo-2: "**W**{: .day}[1.3 Midpoint and Distance](./geometry/1-3-midpoint-and-distance.html)"
geo-3: "**F**{: .day}1.1–1.3 Review/Quiz"
geo-x: "Sep. 25"

pro-h: "**Intro to Programming**<br>
        [<i class=\"fa-solid fa-file-lines\"></i>](./intro-to-programming/intro-to-programming-syllabus.html){: title=\"Course Syllabus\"}
        [<i class=\"fa-solid fa-globe\"></i>](https://academy.cs.cmu.edu/){: target=\"_blank\" title=\"CS Academy Online Curriculum\"}"
pro-1: "**≥ A**{: .day}Continue working on Unit 1"
pro-2: "**≥ B**{: .day}Continue working on Unit 1"
pro-3: "**< B**{: .day}Continue working on Unit 1"
pro-x: "–"

sta-h: "[**Prob. & Stats**](./prob-and-stats/){: title=\"Course Page\"}<br>
        [<i class=\"fa-solid fa-file-lines\"></i>](./prob-and-stats/prob-and-stats-syllabus.html){: title=\"Course Syllabus\"}
        [<i class=\"fa-solid fa-globe\"></i>](https://openstax.org/books/statistics/pages/1-introduction){: target=\"_blank\" title=\"OpenStax Statistics Online Book\"}"
sta-1: "**T**{: .day}[1.3 Frequency, Frequency Tables, and Levels of Measurement](./prob-and-stats/1-3-frequency-tables.html)"
sta-2: "**R**{: .day}[1.4 Experimental Design and Ethics](./prob-and-stats/1-4-experimental-design-and-ethics.html)"
sta-3: ""
sta-x: "Sep. 28"
sta-e: "[*Duke Farms permission slips due 9/28*](./pdfs/field-trip-permission-slip-for-duke-farms.pdf){: .this-week-extra target=\"_blank\"}"